import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import logoCircle from "../public/image/logoCircle.svg";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>safeMe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
      <Image
          width={140}
          height={140}
          className={styles.circle}
          src={logoCircle}
        ></Image>
        <div className={styles.logo}>
        </div>
      
      </header>
      <main className={styles.main}>
        <div className={styles.baseMain}>
          <div className={styles.textBase}>
            <div className={styles.texto}>
              <h1 className={styles.busqueMsg} >Busque cuidados imediatos perto de <span className={styles.voce} >VOCÊ</span></h1>
           
            </div>
            <button className={styles.button}>Login</button>
          </div>
          <div className={styles.avatarsBase}></div>
        </div>
      </main>
    </div>
  );
}
